import {
  mdiAccountCircle,
  mdiPlus,
  mdiArrowLeft,
  mdiArrowRight,
  mdiAttachment,
  mdiCalendarToday,
  mdiPhone,
  mdiCamera,
  mdiCheck,
  mdiClose,
  mdiDelete,
  mdiDownload,
  mdiPencil,
  mdiCalendar,
  mdiAlertCircle,
  mdiFastForward,
  mdiHeart,
  mdiHeartOff,
  mdiFolder,
  mdiHelp,
  mdiHome,
  mdiInformation,
  mdiMapMarker,
  mdiLock,
  mdiLockOpen,
  mdiMail,
  mdiMenu,
  mdiDotsVertical,
  mdiDotsHorizontal,
  mdiBellOff,
  mdiBell,
  mdiPause,
  mdiCreditCard,
  mdiAccount,
  mdiImage,
  mdiPlay,
  mdiPrinter,
  mdiRefresh,
  mdiRewind,
  mdiMagnify,
  mdiSend,
  mdiCog,
  mdiShare,
  mdiCart,
  mdiSkipNext,
  mdiSkipPrevious,
  mdiStar,
  mdiStarHalf,
  mdiStarOff,
  mdiStop,
  mdiUpload,
  mdiEye,
  mdiEyeOff,
  mdiVolumeLow,
  mdiVolumeMute,
  mdiVolumeOff,
  mdiVolumeHigh,
  mdiAlert,
} from "@mdi/js";

export const iconMap: Record<string, string> = {
  accountCircle: mdiAccountCircle,
  add: mdiPlus,
  arrowBack: mdiArrowLeft,
  arrowForward: mdiArrowRight,
  attachFile: mdiAttachment,
  calendarToday: mdiCalendarToday,
  call: mdiPhone,
  camera: mdiCamera,
  check: mdiCheck,
  close: mdiClose,
  delete: mdiDelete,
  download: mdiDownload,
  edit: mdiPencil,
  event: mdiCalendar,
  error: mdiAlertCircle,
  fastForward: mdiFastForward,
  favorite: mdiHeart,
  favoriteOff: mdiHeartOff,
  folder: mdiFolder,
  help: mdiHelp,
  home: mdiHome,
  info: mdiInformation,
  locationOn: mdiMapMarker,
  lock: mdiLock,
  lockOpen: mdiLockOpen,
  mail: mdiMail,
  menu: mdiMenu,
  moreVert: mdiDotsVertical,
  moreHoriz: mdiDotsHorizontal,
  notificationsOff: mdiBellOff,
  notifications: mdiBell,
  pause: mdiPause,
  payment: mdiCreditCard,
  person: mdiAccount,
  phone: mdiPhone,
  photo: mdiImage,
  play: mdiPlay,
  print: mdiPrinter,
  refresh: mdiRefresh,
  rewind: mdiRewind,
  search: mdiMagnify,
  send: mdiSend,
  settings: mdiCog,
  share: mdiShare,
  shoppingCart: mdiCart,
  skipNext: mdiSkipNext,
  skipPrevious: mdiSkipPrevious,
  star: mdiStar,
  starHalf: mdiStarHalf,
  starOff: mdiStarOff,
  stop: mdiStop,
  upload: mdiUpload,
  visibility: mdiEye,
  visibilityOff: mdiEyeOff,
  volumeDown: mdiVolumeLow,
  volumeMute: mdiVolumeMute,
  volumeOff: mdiVolumeOff,
  volumeUp: mdiVolumeHigh,
  warning: mdiAlert,
};
